### ISSUE TITLE
LDAP Connection is Not Re-established After Timeout

### ISSUE THREAD

**Issue by mbillow** [liam-middlebrook/csh_ldap#3]
After the TCP connect to the LDAP server times out, the library does not make an attempt to reconnect.

`ldap.SERVER_DOWN: {'desc': "Can't contact LDAP server"}`

**Comment by liam-middlebrook** [comment]
Uploaded to PyPi As [1.2.1](https://pypi.python.org/pypi/csh_ldap/1.2.1.dev37)
